version: '3.3'

services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '15432:5432'
    volumes:
        - ./schema-init:/docker-entrypoint-initdb.d
