version: '3.3'

services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 'hr'
      POSTGRES_USER: 'hr'
      POSTGRES_DATABASE: 'hr'
    ports:
      - '5432:5432'
    volumes:
        - ./schema-init:/docker-entrypoint-initdb.d
