version: '3.3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'hr'
      MYSQL_USER: 'hr'
      MYSQL_PASSWORD: 'hr'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'